import Play from './play.svg'
import ArrowUpRight from './arrow-up-right.svg'
import ArrowUpRightWhite from './arrow-up-right-white.svg'
import IconSvg1 from './icon-1.svg'
import IconSvg2 from './icon-2.svg'
import IconSvg3 from './icon-3.svg'
import IconSvg4 from './icon-4.svg'
import IconSvg5 from './icon-5.svg'
import IconSvg6 from './icon-6.svg'
import ArrowRight from './arrow-right.svg'
import Menu from './menu.svg'
import Check from './check.svg'
import Quote from './quote.svg'
import Star from './star.svg'
import User from './user-add.svg'
import Clock from './clock.svg'
import ArrowUp from './arrow-sm-up.svg'
import Facebook from './facebook.svg'
import Instagram from './instagram.svg'
import Youtube from './youtube.svg'
import Tiktok from './tiktok.svg'
import Close from './close.svg'


export {Play, Menu, ArrowUpRight, ArrowUpRightWhite, IconSvg1, IconSvg2, IconSvg3, IconSvg4, IconSvg5, IconSvg6, ArrowRight, Check, Quote, Star, User, Clock, ArrowUp, Facebook, Instagram, Youtube, Tiktok, Close}